#!/usr/bin/env python3
import traceback
from threading  import Thread
from time import sleep

def errorer():
    while True:
        sleep(5)
        raise KeyboardInterrupt

if __name__ == "__main__":
    try: Thread(target=errorer,daemon=True).start()
    except: traceback.print_exc()
    while True:
        sleep(1)
        print('working')
